### PR TITLE
Fix cops naming

### PR DESCRIPTION
**Pull request by HLFH**
To match new cops naming in latest version of `rubocop`.

### CODE REVIEW

**Comment by ericqweinstein** [comment]
@HLFH This looks reasonable to me. Do you know if RuboCop is maintaining compatibility for the old aliases (even if they issue a deprecation warning)? Otherwise, we'll probably need to pin the `rubocop` dependency in the `Gemfile` so anyone depending on an older version of RuboCop can still use earlier versions.

**Comment by HLFH** [comment]
@ericqweinstein When you do `bundle exec ruumba -De`, you don't get a warning but an error:

>Error: The `Layout/TrailingBlankLines` cop has been renamed to `Layout/TrailingEmptyLines`.
>(obsolete configuration found in /Users/hlfh/Desktop/book-explorer/.ruumba.yml, please update it)

The same happens when you run `bundle exec rubocop`:

>Error: The `Layout/TrailingBlankLines` cop has been renamed to `Layout/TrailingEmptyLines`.
>(obsolete configuration found in .rubocop.yml, please update it)

The related Rubocop PR is here: https://github.com/rubocop-hq/rubocop/pull/7468

It has been released for Rubocop 0.77: https://github.com/rubocop-hq/rubocop/releases/tag/v0.77.0

Anyone having rubocop < 0.77 should be able to use the previous conf., and anyone having rubocop >= 0.77 has to use the new naming for the conf.

**Comment by HLFH** [comment]
@ericqweinstein Hi. Any updates? Thanks

**Comment by ericqweinstein** [comment]
Sorry, things have been crazy at work. This looks reasonable to me; I'll merge. Thanks for contributing!

**Pull request merged**
