### PR TITLE
Implement --auto-correct

### LINKED ISSUE #1: Add autofix option
Rubocop has autofix option `-a`. It is very useful for legacy projects.

Can you add it to `ruumba`?

### PR DESCRIPTION
**Pull request by aclemons**
This is experimental and it does break on some complex views, but I have had good results for most things.

Keen to get some review feedback on this. There are probably some better ways to structure the code.

Closes #1

### CODE REVIEW

**Comment by ericqweinstein** [comment]
@aclemons This looks reasonable to me! I'll go through it this week/weekend and we should be able to merge sometime next week. 👍🙏

**Comment by aclemons** [comment]
Any news here?

**Comment by ericqweinstein** [comment]
@aclemons Thanks for your patience! (Personal life stuff gets in the way sometimes.) This generally LGTM—any tests we may still need to add for `lib/ruumba/correctors.rb`?

**Comment by ericqweinstein** [comment]
@aclemons LGTM aside from the question re: any tests we may still need to add for `lib/ruumba/correctors.rb` 👍

**Comment by aclemons** [comment]
Sorry for the delay. I have added some specs for the correctors now and this should be ready to merge. I have included a revert of 6581acd since the build is red and best I can tell, ruumba already handled this without needing any special code like this.

**Comment by ericqweinstein** [comment]
@aclemons Thanks for this! Feel free to ignore my comment on #38, then.

**Comment by ericqweinstein** [comment]
Looks good! I'll cut a new tag and push to RubyGems tonight.

**Pull request merged**
